### ISSUE TITLE
Pluma usage much memory

### ISSUE THREAD

**Issue by lcharles123** [mate-desktop/pluma#116] opened 2015-05-15 23:41 UTC
This problem appeared suddenly, it's using more than 500MB of RAM in blank and a peak of 100% CPU when i start or open a tab.

I use Linux Mint 17.1 x64

If someone wants, can tell me how to get logs?

Thanks!

**Comment by jrgp** [comment] 2015-05-25 09:46
If this is reproducable, valgrind/strace/lsof and friends should help you dig deeper to find the root cause.

**Comment by monsta** [comment] 2015-06-02 11:28
Check the ownership of ```/run/user/1000/dconf/user``` - is it owned by you or by ```root:root```?

**Comment by lcharles123** [comment] 2015-06-18 00:01
The /run/user/1000/dconf/user file is normal user, not root.

But it "suddenly" returned to normal, the peak of the CPU occurred when i saved files using pluma, Firefox or Libreoffice, or visualized using gThumb; but only Pluma used too much memory.

So this issue is not in the core plume.

This should be a problem in file manager packages.
Now the system is running smoothly, this issue has been resolved.
Thanks for the great software.
:)

**Comment by monsta** [comment] 2015-09-08 15:23
Ok, you can close this issue then.

**Closed** 2015-09-08 17:03 UTC
