### ISSUE TITLE
file not loaded from last location

### ISSUE THREAD

**Issue by philipzae** [mate-desktop/pluma#79] opened 2014-04-17 07:23 UTC
when i open a file with pluma and then move the cursor to a location and then close pluma and then reopen the file again in pluma, the cursor location is restored. but if i open up two or more files, only the cursor position of the first file will be restored.

**Comment by sleeveroller** [comment] 2015-06-26 08:27
I can't reproduce this on Debian Sid - Pluma 1.8.1. I've tried it with 1,2 and 3 files and they all load with the cursor at the correct position.

If this is still an issue could you confirm which distro and version of Pluma you are using.

**Comment by flexiondotorg** [comment] 2015-06-26 11:49
I can't reproduce this either. Closing for now, but if new information is forth coming we can reopen.

**Closed by flexiondotorg** 2015-06-26 11:49 UTC

**Comment by philipzae** [comment] 2015-07-03 19:56
So it seems the issue can be seen even with a single text file as well in Pluma 1.8.1 on Linux Mint 17.1. So i was mistaken to think that the cursor didnt restore in the correct location as it does, but the window scroll position in the document isnt in the right location, as it always has the scroll position at the top of the document, even though the cursor position is further down in the text file.

Steps:
1) Open Pluma
2) Open a text file that is longer than the screen height
3) Move the cursor to the last line of the file
4) Close the file by clicking on the 'X' in the tab or press Ctrl+W
5) Click on the open toolbar buttons drop down menu to reopen the text file
6) The window will show the top of the text file, though the cursor is at the bottom of the text file
7) Close pluma
8) Open the text file by double clicking on it in caja
9) Pluma will open with the window showing the bottom of the text file

Screencast
https://drive.google.com/file/d/0B6qJrVIa0SAlLXktOVhBZ0M5SlE/view?usp=sharing
