### ISSUE TITLE
unsaved changes dialog often requires selecting "Close without Saving" twice

### ISSUE THREAD

**Issue by stiunnif** [mate-desktop/pluma#356] opened 2018-08-17 22:25 UTC
#### Expected behaviour
when "Close without Saving" button is selected, the dialog and pluma window should immediately close.

#### Actual behaviour
often, when the "Close without Saving" button is selected, the unsaved changes dialog comes up a second time (or perhaps the original dialog is modified in place)

note: the "second dialog" (if it is in fact a second dialog) is about a line shorter than the first one, if that's some clue. also, in instances where the second instance of the dialog isn't persistently shown, a keen eye may notice that the shorter second dialog flashes quickly before pluma closes out.

also, the second dialog has "Close without Saving" highlighted, rather than the original default of "Save", which may be another clue (e.g., is this a second dialog vs is it the same dialog but modified)

i didn't used to encounter this issue in pluma, but it's been going on for quite a while now (several months, or perhaps even a year or more)

#### Steps to reproduce the behaviour
note: the second dialog does not consistently appear persistently (although it does seem to consistently get shown momentarily in instances where it doesn't persist, as described above) ...

prep: 

- create file named "docOne" with content: "[original docOne text]"
- create file named "docTwo" with content: "[original docTwo text]"
- save these files and close pluma

1. open "docOne"
2. type something in "docOne" without saving
3. open "docTwo"
4. type something in "docTwo" without saving
5. close pluma - select "Close without Saving" - watch carefully to see second (shorter) instance of unsaved changes dialog flash before the pluma window closes (or, the second instance may persist, requiring you to select "Close without Saving" a second time)

screen capture showing first unsaved changes dialog:
![first-dialog](https://user-images.githubusercontent.com/42481165/44291027-c074ea00-a249-11e8-8950-8089414d64f2.png)

screen capture showing second unsaved changes dialog:
![second-dialog](https://user-images.githubusercontent.com/42481165/44291032-c965bb80-a249-11e8-8838-932f38a9359c.png)

#### MATE general version
1.20.2

#### Package version
1.20.2-2

#### Linux Distribution
Fedora 28

**Comment by lukefromdc** [comment] 2018-08-18 17:55
With Pluma 1.21.1 from git master running on Debian Unstable I was unable to duplicate this, wonder what is different?

**Comment by sc0w** [comment] 2018-08-18 18:45
I can reproduce the issue (old issue for me) in pluma 1.21.1

**Comment by lukefromdc** [comment] 2018-08-18 19:45
Oh THAT's interesting. No theme should be able to have any effect on this kind of bug. 

I just confirmed this does in fact happen in TOK, but not with my UbuntuStudio_Legacy theme that shares much code with BlackMATE. Menta is OK, Blue_Submarine is OK, BlackMATE already reported OK,  Greybiurd is OK-and the High Contrast themes have this problem. Since at least one non-MATE theme has this problem it will have to be fixed in Pluma itself

**Comment by raveit65** [comment] 2018-08-19 12:44
Issue is caused by using `theme_text_color` in button settings.
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/TraditionalOk/gtk-3.0/gtk-widgets.css#L1011
```
button {
    color: @theme_text_color;
    border-style: solid;
    border-color: transparent;
}
```
Using `theme_fg_color` fixes the problem.
```
button {
    color: @theme_fg_color;
    border-style: solid;
    border-color: transparent;
}
```
But color definition is different!
@stiunnif 
Is this TraditionalOK theme in your screenshots?

**Comment by stiunnif** [comment] 2018-08-19 15:01
@raveit65 - yes, the controls are "TraditionalOk" (window border in screenshots is "Shiny")

**Comment by sc0w** [comment] 2018-08-20 15:53
@raveit65 yes, your fix works.

In pluma code, in the function `build_multiple_docs_dialog` of file `pluma-close-confirmation-dialog.c`:

`gtk_container_set_resize_mode (GTK_CONTAINER (hbox),GTK_RESIZE_IMMEDIATE);`

or

`gtk_container_set_resize_mode (GTK_CONTAINER (scrolledwindow), GTK_RESIZE_IMMEDIATE);`

works, but `gtk_container_set_resize_mode` is deprecated.

**Comment by sc0w** [comment] 2018-08-20 17:31
The issue happens in themes with different colors in the fonts of buttons unpressed and pressed.

I mean, this black fonts seems to be the same, but are different `[rgb (0,0,0) grb (26,26,26)]`, and makes the issue on click:

![screenshot at 2018-08-20 19-26-54](https://user-images.githubusercontent.com/7734191/44356401-8dcc2b00-a4af-11e8-9c00-e8dda09bd8f9.png)

same issue in highcontrast inverse theme.

**Comment by raveit65** [comment] 2018-08-20 19:47
I think `button {}`and `button.default {}` have to use theme_fg_color for some reasons.
I can trigger the issue with Menta theme if i change one or both settings to something other than theme_fg_color.
Eg. theme_text_color, but Menta use the same color for theme_text_color and theme_fg_color.
`@define-color theme_fg_color @theme_text_color;`

**Closed** 2018-08-21 14:53 UTC
Labels: confirmed

**Comment by palosBA** [comment] 2018-12-17 11:05
Pluma 1.20.3 doesn't resize the whole dialog window, but after pressing and holding Alt key (to display keyboard accelerators) the file list is resized and scrollbars appear:
![pluma-close](https://user-images.githubusercontent.com/7702948/50083282-87e31e00-01f3-11e9-82ab-561bf9551847.gif)
